{% set name = "htm-pytorch" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/htm-pytorch-{{ version }}.tar.gz
  sha256: 9ca11f01414cc72c4949e39d0672078353a6e5bcbe2ff0a97ec1fadb81e234b1

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - einops >=0.3
    - python >={{ python_min }}
    - pytorch >=1.6

test:
  imports:
    - htm_pytorch
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucidrains/htm-pytorch
  summary: Hierarchical Transformer Memory for Pytorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
